export type Message = {
    ID: BigInt,
    channelID: BigInt,
    guildID: BigInt,
    author: Object,
    member: Object,
    content: String,
    timestamp: Number | Date,
    editedTimestamp: Number | Date,
    tts: Boolean,
    mentionEveryone: Boolean,
    mentions: Array<Object>,
    mentionRoles: Array<Object>,
    attachments: Array<Object>,
    embeds: Array<Object>,
    reactions: Array<Object>,
    nonce: Number | String,
    pinned: Boolean,
    webhookID: Boolean,
    type: Number,
    activity: Object,
    application: Object,
    applicationID: BigInt,
    messageReference: Object,
    flags: Number,
    referencedMessage: Object,
    interaction: Object,
    thread: Object,
    components: Array,
    stickerItems: Array<Object>,
    stickers: Array<Object>
}

export type Guild = {
    ID: BigInt,
    name: String,
    icon: String,
    iconHash: String,
    splash: String,
    discoverySplash: String,
    ownerID: BigInt,
    region: String,
    afkChannelID: BigInt,
    afkTimeout: Number,
    widgetEnabled: Boolean,
    widgetChannelId: BigInt,
    verificationLevel: Number,
    defaultMessageNotification: Number,
    explicitContentFilter: Number,
    roles: Array<Object>,
    emojis: Array<Object>,
    features: Array<String>,
    mfaLevel: Number,
    applicationID: BigInt,
    systemChannelID: BigInt,
    systemChannelFlags: Number,
    rulesChannelID: BigInt,
    joinedAt: Number | Date,
    large: Boolean,
    unavailable: Boolean,
    memberCount: Number,
    voiceStates: Array<Object>,
    members: Array<Object>,
    channels: Array<Object>,
    threads: Array<Object>,
    presences: Array<Object>,
    maxPresences: Number,
    maxMembers: Number,
    vanityUrlCode: String,
    description: String,
    banner: String,
    premiumTier: Number,
    premiumSubscriptionCount: Number,
    preferredLocale: String,
    publicUpdatesChannelID: BigInt,
    maxVideoChannelUsers: Number,
    approximateMemberCount: Number,
    approximatePresenceCount: Number,
    welcomeScreen: Object,
    nsfwLevel: Number,
    stageInstances: Array<Object>,
    stickers: Array<Object>
}
