export type Message = {
    ID: BigInt,
    channelID: BigInt,
    guildID: BigInt,
    author: Object,
    member: Object,
    content: String,
    timestamp: Date,
    editedTimestamp: Date,
    tts: Boolean,
    mentionEveryone: Boolean,
    mentions: Array<Object>,
    mentionRoles: Array<Object>,
    attachments: Array<Object>,
    embeds: Array<Object>,
    reactions: Array<Object>,
    nonce: Number | String,
    pinned: Boolean,
    webhookID: Boolean,
    type: Number,
    activity: Object,
    application: Object,
    applicationID: BigInt,
    messageReference: Object,
    flags: Number,
    referencedMessage: Object,
    interaction: Object,
    thread: Object,
    components: Array,
    stickerItems: Array<Object>,
    stickers: Array<Object>
}
